### PR TITLE
Update selected images

### LINKED ISSUE #110: Update trip images

### PR DESCRIPTION
**Pull request by knutm92**
Fixes #110 

I also changed In the Park trip data but I still have to check the remaining ones, so leaving #112 open

### CODE REVIEW

**Comment by knutm92** [comment]
This is a mixture of photos from 3 sources:
-Pawel's repository
-Re-colored old app photos
-Photos taken today

**Review by darowsluk — CHANGES_REQUESTED** [review]
The new images look much much better than before! Great job!

I have a few suggestions below. See if it is feasible to take them into account. If not, we can try to do it in the next patch.

Map Items:
1. mapItem_02.png - center diaspora (looks cut off in the bottom map item)
2. mapItem_03.png - crop higher (the paupertas sign is cut on full view, because of the frame)
3. mapItem_04.png - very good
4. mapItem_05.png - center Jordan (looks cut off in the bottom map item)
5. mapItem_06.png - center altanka (looks a bit cut off in the bottom map item)
6. mapItem_07.png - good, but would be better if the leaves were green (spring)
7. mapItem_08.png - very good
8. mapItem_10.png - excellent !!!
9. mapItem_11.png - good

Trip 01:
1. ok
2. ok
3. ok
4. ok
5. ok
6. ok
7. Father Jordan is too far to the left (head is covered by points) - use the rule of two thirds
8. ok
9. ok
10. ok
11. ok
12. ok
13. ok
14. ok
15. ok
16. ok
17. ok
18. ok
19. ok
20. small figure - hard to see on a small screen (crop to better see keys)
21. small figure - hard to see on a small screen (crop to better see sword)
22. ok
23. ok
24. ok
25. ok
26. sign Paupertas on the bottom is cut because of the frame
27. ok
28. ok
29. do we have image with green leaves?
30. ok
31. ok
32. ok
33. ok
34. ok
35. ok
36. ok

**Comment by knutm92** [comment]
Thank you for the feedback- I have fixed all of the suggested points that I was able to change..

**Review by darowsluk — APPROVED** [review]
Looks great! Let's merge.

**Pull request merged**
