### PR TITLE
Fix various

### LINKED ISSUE #38: Fix flicker on loading trips
As a user
I see flicker when loading step images for trips.

**Steps to reproduce:**
1. Open "In Park" trip
2. Click on the forward navigation
3. The title of the next frame will be shortly visible before the image loads (causing flicker)

### LINKED ISSUE #49: Code phone rotation block
As user
I want to have my phone app working only in vertical position

**Requirements:**
1. Disabled rotation of phone to horizontal position for the entire app.

### LINKED ISSUE #56: Fix Way of the cross picture alignment
As a user
I see clipped pictures on Way of the cross trip.

**Steps to reproduce:**

1. Open "Way of the cross" trip
2. Pictures are clipped and white background does not sufficiently contrast with the text background

### PR DESCRIPTION
**Pull request by darowsluk**
fix #38 
fix #49 
fix #56

### CODE REVIEW

**Comment by knutm92** [comment]
Interesting idea with the contrasting background for the way of the cross photos. It looks nice with the regular-shaped photos (like station VI), but I am wondering whether there is a way to make the transition between the photo and the background smoother or force a more regular shape (for instance in station II or XI)?

**Comment by darowsluk** [comment]
> force a more regular shape

Is this update going in the right direction?

**Comment by knutm92** [comment]
> > force a more regular shape
> 
> Is this update going in the right direction?

I think the proposed design looks neat 👍

**Review by knutm92 — APPROVED** [review]
The code and pics look good, let's merge.

**Pull request merged**
